# Generated by Django 2.2.6 on 2020-05-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('type_of_post', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('owner', models.TextField()),
            ],
        ),
    ]
